export interface User {
  id: string;
  name: string;
  balance: number;
}

export interface Bet {
  userId: string;
  number: number;
  amount: number;
}

/**
 * The main data structure for the game
 */
export interface GameState {
  rngResult: number | null; // Random number generated by the wheel
  tableState: Bet[]; // List of all bets on the table
  users: { [key: string]: User };
  isBettingOpen: boolean;
  timeLeft: number; // Synchronized timer (Timer starts at 15 seconds)
}

/**
 * D1 : Snapshot of a turn to make it transactional. 
 */
export interface RoundSnapshot {
  roundId: string;
  rngResult: number;
  bets: Bet[];
  resolvedAt: Date | null;  // null = not resolved yet
}

// Persistence 
export interface IUserRepository {
  findUserById(userId: string): Promise<User | null>;
  // Persistence of the balance of a user
  saveBalance(userId: string, balance: number): Promise<void>;
  // Persistence of the turn snapshot
  saveRoundSnapshot(snapshot: RoundSnapshot): Promise<void>;
  // Mark a turn as resolved
  markRoundResolved(roundId: string): Promise<void>;
  // Return the last turn unresolved if a crash happen
  getUnresolvedRound(): Promise<RoundSnapshot | null>;
}
