// Represents the available roulette board types
export type BoardType = 'european' | 'mini';

export interface User {
  id: string;
  name: string;
  balance: number;
  password: string;
  // Player selected board
  boardType?: BoardType;
  lastWin?: number;
}

export interface Bet {
  userId: string;
  number: number;
  password: string;
  amount: number;
  // Board where the bet was placed
  boardType: BoardType;
}

// Winner information for one round
export interface RoundWinner {
  userId: string;
  playerName: string;
  gain: number;
  winningNumber: number;
  boardType: BoardType;
}

/**
 * The main data structure for the game
 */
export interface GameState {
  //rngResult: number | null; // Random number generated by the wheel
  //tableState: Bet[]; // List of all bets on the table
  users: { [key: string]: User };
  //isBettingOpen: boolean;
  //timeLeft: number; // Synchronized timer (Timer starts at 15 seconds)
  //board: BoardConfig; // Current roulette board configuration
  timeLeft : number;
  boards : { [key in BoardType]: BoardState}
}

/**
 * D1 : Snapshot of a turn to make it transactional.
 */
export interface RoundSnapshot {
  roundId: string;
  boardType: BoardType;
  rngResult: number;
  bets: Bet[];
  resolvedAt: Date | null; // null = not resolved yet
}

// Defines the numbers available for a roulette board
export interface BoardConfig {
  type: BoardType;
  numbers: number[];
}

// Single board state
export interface BoardState {
  rngResult: number | null;
  tableState: Bet[];
  isBettingOpen: boolean;
  board: BoardConfig;
}

// Persistence
export interface IUserRepository {
  // Find one user with his id
  findUserById(userId: string): Promise<User | null>;
  // Return all saved users
  findAllUsers(): Promise<User[]>;
  // Save or update one user
  saveUser(user: User): Promise<void>;
  // Save the balance of a user
  saveBalance(userId: string, balance: number): Promise<void>;
  // Save the snapshot of one round
  saveRoundSnapshot(snapshot: RoundSnapshot): Promise<void>;
  // Mark one round as resolved
  markRoundResolved(roundId: string): Promise<void>;
  // Return one unresolved round after a crash
  getUnresolvedRound(): Promise<RoundSnapshot | null>;
}